server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: microservice-collecte
          uri: lb://MICROSERVICE-COLLECTE
          predicates:
            - Path=/api/collecte/**
          filters:
            - StripPrefix=2
        - id: microservice-analyse
          uri: lb://MICROSERVICE-ANALYSE
          predicates:
            - Path=/api/analyse/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
